services:
  kong:
    ports:
      - "8002:8002"
      - "8001:8001"
      - "8000:8000"
    build: .
    environment:
      KONG_ADMIN_GUI_PATH: '/'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002/'
      KONG_PLUGINS: 'bundled,middleman,mockup,budget'
      KONG_DATABASE: 'postgres'
      KONG_PG_HOST: 'db'
      KONG_PG_USER: ${DBUSER}
      KONG_PG_PASSWORD: ${DBPW}
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
    depends_on:
      - db
    networks:
      - kong-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    container_name: 'db'
    image: postgres:11.2
    environment:
      POSTGRES_DB: 'kong'
      POSTGRES_PASSWORD: ${DBPW}
      POSTGRES_USER: ${DBUSER}
    networks:
      - kong-network
networks:
  kong-network: